### ISSUE TITLE
Is it possible to use it on the client-side ?

### ISSUE THREAD

**Issue by vasco3** [wooorm/retext-spell#16]
I would like to check spelling on an online editor in a web app. 
I see that the dictionaries use file-system. Is there a way to bypass that?

**Comment by wooorm** [comment]
Yep, it’s possible, but then you need to find some way to load the dictionaries indeed. You could, instead of something like `require('dictionary-nl')`, use `fs.readFile` in combination with something like [brfs](https://github.com/browserify/brfs) with browserify instead. Other bundlers probably have similar features.

**Comment by vasco3** [comment]
Awesome, that helps! Dank u zeer

**Comment by wooorm** [comment]
Asjeblieft!

**Comment by vasco3** [comment]
I ended up loading the dictionary as js files stored in a string template.
And in the utility function I had to mimick the `load` function from the woorm dictionaries

```js
 const spell = retext()
    .use(retextSpell, callback => {
      callback(null, {
        aff: en_us_aff,
        dic: en_us_dic,
      });
    })
    .use(retextSyntaxUrls);
```

works perfectly 🎉
