### ISSUE TITLE
Ignore RegExp

### ISSUE THREAD

**Issue by agentofuser** [wooorm/retext-spell#17]
Would there be interest in a PR allowing regexps as well as strings in the `ignore` array?

Example use-case: ignoring names of html headings like `/h\d/`.

**Comment by wooorm** [comment]
Maybe, yeah, I think that could make sense.

It would add some more logic (dropping the lodash function, iterating over all values in `ignore`, and then testing them all), and it’s not *super* important because it’s already possible to provide `['h1', 'h2',  ...]`.

And last, did you look at providing a [personal dictionary](https://github.com/retextjs/retext-spell#optionspersonal)?

**Comment by agentofuser** [comment]
Yeah, I also feel weird mixing types in the same array. My use case doesn't justify the added complexity/inelegance. Also yes, personal dictionaries are great :)

**Comment by wooorm** [comment]
Alright, thanks for the issue though, please raise more if you run into other things!
